model:
  class_path: mst.system.System
  init_args:
    active_eq_step: 50000
    active_compressor_step: 100000
    active_fx_bus_step: 10000000
    active_master_bus_step: 300000
    mix_fn: mst.mixing.naive_random_mix
    generate_mix_console:
      class_path: mst.modules.AdvancedMixConsole
      init_args:
        sample_rate: 44100
        min_gain_db: -12.0
        max_gain_db: 12.0
        eq_min_gain_db: -12.0
        eq_max_gain_db: 12.0
        min_pan: 0.0
        max_pan: 1.0
    model:
      class_path: mst.modules.MixStyleTransferModel
      init_args:
        track_encoder: 
          class_path: mst.modules.SpectrogramResNetEncoder
          init_args:
            embed_dim: 128
            n_fft: 2048
            hop_length: 512
            input_batchnorm: false
        mix_encoder: 
          class_path: mst.modules.SpectrogramResNetEncoder
          init_args:
            embed_dim: 128
            n_fft: 2048
            hop_length: 512
            input_batchnorm: false
        controller:
          class_path: mst.modules.TransformerController
          init_args:
            embed_dim: 128
            num_track_control_params: 27
            num_fx_bus_control_params: 25
            num_master_bus_control_params: 25
            num_layers: 6
            nhead: 8
        mix_console:
          class_path: mst.modules.AdvancedMixConsole
          init_args:
            sample_rate: 44100
            min_gain_db: -12.0
            max_gain_db: 12.0
            eq_min_gain_db: -12.0
            eq_max_gain_db: 12.0
            min_pan: 0.0
            max_pan: 1.0
    loss: 
      class_path: auraloss.freq.SumAndDifferenceSTFTLoss
      init_args:
        fft_sizes: 
        - 512
        - 2048
        - 8192
        hop_sizes: 
        - 256 
        - 1024
        - 4096
        win_lengths:
        - 512
        - 2048
        - 8192


    
