model:
  class_path: mst.system.System
  init_args:
    mix_fn: mst.mixing.naive_random_mix
    generate_mix_console:
      class_path: mst.modules.AdvancedMixConsole
      init_args:
        sample_rate: 44100
        min_gain_db: -80.0
        max_gain_db: 24.0
        eq_min_gain_db: -12.0
        eq_max_gain_db: 12.0
        min_pan: 0.0
        max_pan: 1.0
    model:
      class_path: mst.modules.MixStyleTransferModel
      init_args:
        track_encoder: 
          class_path: mst.modules.SpectrogramResNetEncoder
          init_args:
            embed_dim: 128
            n_fft: 2048
            hop_length: 512
            input_batchnorm: false
        mix_encoder: 
          class_path: mst.modules.SpectrogramResNetEncoder
          init_args:
            embed_dim: 128
            n_fft: 2048
            hop_length: 512
            input_batchnorm: false
        controller:
          class_path: mst.modules.TransformerController
          init_args:
            embed_dim: 128
            num_control_params: 26
            num_layers: 6
            nhead: 8
        mix_console:
          class_path: mst.modules.AdvancedMixConsole
          init_args:
            sample_rate: 44100
            min_gain_db: -80.0
            max_gain_db: 24.0
            eq_min_gain_db: -24.0
            eq_max_gain_db: 24.0
            min_pan: 0.0
            max_pan: 1.0
    loss: 
      class_path: auraloss.freq.MultiResolutionSTFTLoss
      init_args:
        fft_sizes: 
        - 512
        - 2048
        - 8192
        hop_sizes: 
        - 256 
        - 1024
        - 4096
        win_lengths:
        - 512
        - 2048
        - 8192
        w_sc: 0.0
        w_phs: 0.0
        w_lin_mag: 1.0
        w_log_mag: 1.0
       