model:
  class_path: mst.param_system.ParameterEstimationSystem
  init_args:
    mix_console:
      class_path: mst.modules.AdvancedMixConsole
      init_args:
        sample_rate: 44100
        input_min_gain_db: -48.0
        input_max_gain_db: 48.0
        output_min_gain_db: -48.0
        output_max_gain_db: 48.0
        eq_min_gain_db: -12.0
        eq_max_gain_db: 12.0
        min_pan: 0.0
        max_pan: 1.0
    remixer: 
      class_path: mst.modules.Remixer
      init_args:
        sample_rate: 44100
    encoder:
      class_path: mst.modules.SpectrogramEncoder
      init_args:
        embed_dim: 1024
        n_inputs: 1
    projector:
      class_path: mst.modules.ParameterProjector
      init_args:
        embed_dim: 2048
        num_tracks: 8
        num_track_control_params: 27
        num_fx_bus_control_params: 25
        num_master_bus_control_params: 26



    
