seed_everything: 42
#ckpt_path: /import/c4dm-datasets-ext/Diff-MST/DiffMST/4bjbp29c/checkpoints/epoch=118-step=148750.ckpt

trainer:
  logger: 
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: DiffMST
      save_dir: /import/c4dm-datasets-ext/Diff-MST
  enable_checkpointing: true
  callbacks:
    - class_path: mst.callbacks.audio.LogAudioCallback
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args: 
        max_depth: 2
    - class_path: mst.callbacks.mix.LogReferenceMix
      init_args:
        root_dirs: 
          - /import/c4dm-datasets-ext/diffmst-examples/song1/BenFlowers_Ecstasy_Full/
          - /import/c4dm-datasets-ext/diffmst-examples/song2/Kat Wright_By My Side/
          - /import/c4dm-datasets-ext/diffmst-examples/song3/Titanium_HauntedAge_Full/
        ref_mixes: 
          - /import/c4dm-datasets-ext/diffmst-examples/song1/ref/_Feel it all Around_ by Washed Out (Portlandia Theme).mp3
          - /import/c4dm-datasets-ext/diffmst-examples/song2/ref/The Dip - Paddle To The Stars (Lyric Video).mp3
          - /import/c4dm-datasets-ext/diffmst-examples/song3/ref/Architects - _Doomsday_.mp3
  default_root_dir: null
  gradient_clip_val: 10.0
  devices: 1
  check_val_every_n_epoch: 1
  max_steps: 1000000
  log_every_n_steps: 50
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  sync_batchnorm: true
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 2
  benchmark: true
  accumulate_grad_batches: 4
  reload_dataloaders_every_n_epochs: 1

