data:
  class_path: mst.dataloaders.cambridge.CambridgeDataModule
  init_args:
    root_dirs: 
    - /data/scratch/acw639/Cambridge/mixing-secrets
    length: 524288
    batch_size: 2
    num_workers: 8
    train_buffer_size_gb: 2.0
    val_buffer_size_gb: 0.1